In [2]:
#Task 1

from sqlalchemy import create_engine
engine=create_engine('sqlite:///Northwind.sqlite')
from pandas import DataFrame
import pandas as pd

In [3]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data")
df

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
8,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
9,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
10,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
11,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
12,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
13,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
14,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
15,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
16,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
17,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
18,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
19,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
20,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
21,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
22,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
23,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
24,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
25,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
26,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
27,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
28,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32530,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32531,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32532,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32533,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32534,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32535,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32536,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32537,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32538,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32539,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32540,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32541,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32542,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32543,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32544,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32545,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32546,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32547,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32548,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32549,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32550,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32551,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32552,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32553,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32554,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [8]:
df.columns=['age','typeofjob','Empid','status','cgpa','maritalstatus','service','position','race','gender','r1','r2','r3','country','salary']

In [9]:
df.head(5)

,age,typeofjob,Empid,status,cgpa,maritalstatus,service,position,race,gender,r1,r2,r3,country,salary
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [10]:
connection=engine.connect()

In [12]:
create_table_query=connection.execute("""create table data (age int,typeofjob TEXT,
Empid int,
status TEXT,
cgpa int,
maritalstatus TEXT,
service TEXT,
position TEXT,
race TEXT,
gender TEXT,
r1 int,
r2 int,
r3 int,
country TEXT,
salary int)""")

In [13]:
tables=engine.table_names()
print(tables)

['data']

In [14]:
df.to_sql('data', connection,if_exists='replace')

In [200]:
show_table_query=connection.execute("select * from data")
table=pd.DataFrame(show_table_query.fetchall())
print(table)

          0   1                  2       3              4   5   \
0          0  20   Self-emp-not-inc   83311      Bachelors  13
1          1  38         government  215646        HS-grad   9
2          4  37            Private  284582        Masters  14
3          5  49            Private  160187            9th   5
4          6  52   Self-emp-not-inc  209642        HS-grad   9
5          7  31            Private   45781        Masters  14
6          8  42            Private  159449      Bachelors  13
7          9  37            Private  280464   Some-college  10
8         10  30          State-gov  141297      Bachelors  13
9         11  23            Private  122272      Bachelors  13
10        12  32            Private  205019     Assoc-acdm  12
11        13  40            Private  121772      Assoc-voc  11
12        14  34            Private  245487        7th-8th   4
13        15  25   Self-emp-not-inc  176756        HS-grad   9
14        16  32            Private  186824        HS-grad   9
15        17  38            Private   28887           11th   7
16        18  43   Self-emp-not-inc  292175        Masters  14
17        19  40            Private  193524      Doctorate  16
18        20  54            Private  302146        HS-grad   9
19        21  35        Federal-gov   76845            9th   5
20        22  43            Private  117037           11th   7
21        23  59            Private  109015        HS-grad   9
22        24  56          Local-gov  216851      Bachelors  13
23        25  19            Private  168294        HS-grad   9
24        26  54                  ?  180211   Some-college  10
25        27  39            Private  367260        HS-grad   9
26        28  49            Private  193366        HS-grad   9
27        29  23          Local-gov  190709     Assoc-acdm  12
28        30  20            Private  266015   Some-college  10
29        31  45            Private  386940      Bachelors  13
...      ...  ..                ...     ...            ...  ..
32528  32530  30                  ?   33811      Bachelors  13
32529  32531  34            Private  204461      Doctorate  16
32530  32532  54            Private  337992      Bachelors  13
32531  32533  37            Private  179137   Some-college  10
32532  32534  22            Private  325033           12th   8
32533  32535  34            Private  160216      Bachelors  13
32534  32536  30            Private  345898        HS-grad   9
32535  32537  38            Private  139180      Bachelors  13
32536  32538  71                  ?  287372      Doctorate  16
32537  32539  45          State-gov  252208        HS-grad   9
32538  32540  41                  ?  202822        HS-grad   9
32539  32541  72                  ?  129912        HS-grad   9
32540  32542  45          Local-gov  119199     Assoc-acdm  12
32541  32543  31            Private  199655        Masters  14
32542  32544  39          Local-gov  111499     Assoc-acdm  12
32543  32545  37            Private  198216     Assoc-acdm  12
32544  32546  43            Private  260761        HS-grad   9
32545  32547  65   Self-emp-not-inc   99359    Prof-school  15
32546  32548  43          State-gov  255835   Some-college  10
32547  32549  43   Self-emp-not-inc   27242   Some-college  10
32548  32550  32            Private   34066           10th   6
32549  32551  43            Private   84661      Assoc-voc  11
32550  32552  32            Private  116138        Masters  14
32551  32553  53            Private  321865        Masters  14
32552  32554  22            Private  310152   Some-college  10
32553  32555  27            Private  257302     Assoc-acdm  12
32554  32556  40            Private  154374        HS-grad   9
32555  32557  58            Private  151910        HS-grad   9
32556  32558  22            Private  201490        HS-grad   9
32557  32559  52       Self-emp-inc  287927        HS-grad   9

                           6                   7                8   \
0          Married-civ-spouse     Exec-managerial          Husband
1                    Divorced   Handlers-cleaners    Not-in-family
2          Married-civ-spouse     Exec-managerial             Wife
3       Married-spouse-absent       Other-service    Not-in-family
4          Married-civ-spouse     Exec-managerial          Husband
5               Never-married      Prof-specialty    Not-in-family
6          Married-civ-spouse     Exec-managerial          Husband
7          Married-civ-spouse     Exec-managerial          Husband
8          Married-civ-spouse      Prof-specialty          Husband
9               Never-married        Adm-clerical        Own-child
10              Never-married               Sales    Not-in-family
11         Married-civ-spouse        Craft-repair          Husband
12         Married-civ-spouse    Transport-moving          Husband
13              Never-married     Farming-fishing        Own-child
14              Never-married   Machine-op-inspct        Unmarried
15         Married-civ-spouse               Sales          Husband
16                   Divorced     Exec-managerial        Unmarried
17         Married-civ-spouse      Prof-specialty          Husband
18                  Separated       Other-service        Unmarried
19         Married-civ-spouse     Farming-fishing          Husband
20         Married-civ-spouse    Transport-moving          Husband
21                   Divorced        Tech-support        Unmarried
22         Married-civ-spouse        Tech-support          Husband
23              Never-married        Craft-repair        Own-child
24         Married-civ-spouse                   ?          Husband
25                   Divorced     Exec-managerial    Not-in-family
26         Married-civ-spouse        Craft-repair          Husband
27              Never-married     Protective-serv    Not-in-family
28              Never-married               Sales        Own-child
29                   Divorced     Exec-managerial        Own-child
...                       ...                 ...              ...
32528           Never-married                   ?    Not-in-family
32529      Married-civ-spouse      Prof-specialty          Husband
32530      Married-civ-spouse     Exec-managerial          Husband
32531                Divorced        Adm-clerical        Unmarried
32532           Never-married     Protective-serv        Own-child
32533           Never-married     Exec-managerial    Not-in-family
32534           Never-married        Craft-repair    Not-in-family
32535                Divorced      Prof-specialty        Unmarried
32536      Married-civ-spouse                   ?          Husband
32537               Separated        Adm-clerical        Own-child
32538               Separated                   ?    Not-in-family
32539      Married-civ-spouse                   ?          Husband
32540                Divorced      Prof-specialty        Unmarried
32541                Divorced       Other-service    Not-in-family
32542      Married-civ-spouse        Adm-clerical             Wife
32543                Divorced        Tech-support    Not-in-family
32544      Married-civ-spouse   Machine-op-inspct          Husband
32545           Never-married      Prof-specialty    Not-in-family
32546                Divorced        Adm-clerical   Other-relative
32547      Married-civ-spouse        Craft-repair          Husband
32548      Married-civ-spouse   Handlers-cleaners          Husband
32549      Married-civ-spouse               Sales          Husband
32550           Never-married        Tech-support    Not-in-family
32551      Married-civ-spouse     Exec-managerial          Husband
32552           Never-married     Protective-serv    Not-in-family
32553      Married-civ-spouse        Tech-support             Wife
32554      Married-civ-spouse   Machine-op-inspct          Husband
32555                 Widowed        Adm-clerical        Unmarried
32556           Never-married        Adm-clerical        Own-child
32557      Married-civ-spouse     Exec-managerial             Wife

                        9        10     11    12  13              14      15
0                    White     Male      0     0  13   United-States   <=50K
1                    White     Male      0     0  40   United-States   <=50K
2                    White   Female      0     0  40   United-States   <=50K
3                    Black   Female      0     0  16         Jamaica   <=50K
4                    White     Male      0     0  45   United-States    >50K
5                    White   Female  14084     0  50   United-States    >50K
6                    White     Male   5178     0  40   United-States    >50K
7                    Black     Male      0     0  80   United-States    >50K
8       Asian-Pac-Islander     Male      0     0  40           India    >50K
9                    White   Female      0     0  30   United-States   <=50K
10                   Black     Male      0     0  50   United-States   <=50K
11      Asian-Pac-Islander     Male      0     0  40               ?    >50K
12      Amer-Indian-Eskimo     Male      0     0  45          Mexico   <=50K
13                   White     Male      0     0  35   United-States   <=50K
14                   White     Male      0     0  40   United-States   <=50K
15                   White     Male      0     0  50   United-States   <=50K
16                   White   Female      0     0  45   United-States    >50K
17                   White     Male      0     0  60   United-States    >50K
18                   Black   Female      0     0  20   United-States   <=50K
19                   Black     Male      0     0  40   United-States   <=50K
20                   White     Male      0  2042  40   United-States   <=50K
21                   White   Female      0     0  40   United-States   <=50K
22                   White     Male      0     0  40   United-States    >50K
23                   White     Male      0     0  40   United-States   <=50K
24      Asian-Pac-Islander     Male      0     0  60           South    >50K
25                   White     Male      0     0  80   United-States   <=50K
26                   White     Male      0     0  40   United-States   <=50K
27                   White     Male      0     0  52   United-States   <=50K
28                   Black     Male      0     0  44   United-States   <=50K
29                   White     Male      0  1408  40   United-States   <=50K
...                    ...      ...    ...   ...  ..             ...     ...
32528   Asian-Pac-Islander   Female      0     0  99   United-States   <=50K
32529                White     Male      0     0  60   United-States    >50K
32530   Asian-Pac-Islander     Male      0     0  50           Japan    >50K
32531                White   Female      0     0  39   United-States   <=50K
32532                Black     Male      0     0  35   United-States   <=50K
32533                White   Female      0     0  55   United-States    >50K
32534                Black     Male      0     0  46   United-States   <=50K
32535                Black   Female  15020     0  45   United-States    >50K
32536                White     Male      0     0  10   United-States    >50K
32537                White   Female      0     0  40   United-States   <=50K
32538                Black   Female      0     0  32   United-States   <=50K
32539                White     Male      0     0  25   United-States   <=50K
32540                White   Female      0     0  48   United-States   <=50K
32541                Other   Female      0     0  30   United-States   <=50K
32542                White   Female      0     0  20   United-States    >50K
32543                White   Female      0     0  40   United-States   <=50K
32544                White     Male      0     0  40          Mexico   <=50K
32545                White     Male   1086     0  60   United-States   <=50K
32546                White   Female      0     0  40   United-States   <=50K
32547                White     Male      0     0  50   United-States   <=50K
32548   Amer-Indian-Eskimo     Male      0     0  40   United-States   <=50K
32549                White     Male      0     0  45   United-States   <=50K
32550   Asian-Pac-Islander     Male      0     0  11          Taiwan   <=50K
32551                White     Male      0     0  40   United-States    >50K
32552                White     Male      0     0  40   United-States   <=50K
32553                White   Female      0     0  38   United-States   <=50K
32554                White     Male      0     0  40   United-States    >50K
32555                White   Female      0     0  40   United-States   <=50K
32556                White     Male      0     0  20   United-States   <=50K
32557                White   Female  15024     0  40   United-States    >50K

[32558 rows x 16 columns]

In [176]:
table.columns=['rowid','age','typeofjob','Empid','status','cgpa','maritalstatus','service','position','race','gender','r1','r2','r3','country','salary']

In [177]:
table=table.drop(['rowid'],axis=1)

In [178]:
print(table)

       age          typeofjob   Empid         status  cgpa  \
0       50   Self-emp-not-inc   83311      Bachelors    13
1       38            Private  215646        HS-grad     9
2       53            Private  234721           11th     7
3       28            Private  338409      Bachelors    13
4       37            Private  284582        Masters    14
5       49            Private  160187            9th     5
6       52   Self-emp-not-inc  209642        HS-grad     9
7       31            Private   45781        Masters    14
8       42            Private  159449      Bachelors    13
9       37            Private  280464   Some-college    10
10      30          State-gov  141297      Bachelors    13
11      23            Private  122272      Bachelors    13
12      32            Private  205019     Assoc-acdm    12
13      40            Private  121772      Assoc-voc    11
14      34            Private  245487        7th-8th     4
15      25   Self-emp-not-inc  176756        HS-grad     9
16      32            Private  186824        HS-grad     9
17      38            Private   28887           11th     7
18      43   Self-emp-not-inc  292175        Masters    14
19      40            Private  193524      Doctorate    16
20      54            Private  302146        HS-grad     9
21      35        Federal-gov   76845            9th     5
22      43            Private  117037           11th     7
23      59            Private  109015        HS-grad     9
24      56          Local-gov  216851      Bachelors    13
25      19            Private  168294        HS-grad     9
26      54                  ?  180211   Some-college    10
27      39            Private  367260        HS-grad     9
28      49            Private  193366        HS-grad     9
29      23          Local-gov  190709     Assoc-acdm    12
...    ...                ...     ...            ...   ...
32530   30                  ?   33811      Bachelors    13
32531   34            Private  204461      Doctorate    16
32532   54            Private  337992      Bachelors    13
32533   37            Private  179137   Some-college    10
32534   22            Private  325033           12th     8
32535   34            Private  160216      Bachelors    13
32536   30            Private  345898        HS-grad     9
32537   38            Private  139180      Bachelors    13
32538   71                  ?  287372      Doctorate    16
32539   45          State-gov  252208        HS-grad     9
32540   41                  ?  202822        HS-grad     9
32541   72                  ?  129912        HS-grad     9
32542   45          Local-gov  119199     Assoc-acdm    12
32543   31            Private  199655        Masters    14
32544   39          Local-gov  111499     Assoc-acdm    12
32545   37            Private  198216     Assoc-acdm    12
32546   43            Private  260761        HS-grad     9
32547   65   Self-emp-not-inc   99359    Prof-school    15
32548   43          State-gov  255835   Some-college    10
32549   43   Self-emp-not-inc   27242   Some-college    10
32550   32            Private   34066           10th     6
32551   43            Private   84661      Assoc-voc    11
32552   32            Private  116138        Masters    14
32553   53            Private  321865        Masters    14
32554   22            Private  310152   Some-college    10
32555   27            Private  257302     Assoc-acdm    12
32556   40            Private  154374        HS-grad     9
32557   58            Private  151910        HS-grad     9
32558   22            Private  201490        HS-grad     9
32559   52       Self-emp-inc  287927        HS-grad     9

                maritalstatus             service         position  \
0          Married-civ-spouse     Exec-managerial          Husband
1                    Divorced   Handlers-cleaners    Not-in-family
2          Married-civ-spouse   Handlers-cleaners          Husband
3          Married-civ-spouse      Prof-specialty             Wife
4          Married-civ-spouse     Exec-managerial             Wife
5       Married-spouse-absent       Other-service    Not-in-family
6          Married-civ-spouse     Exec-managerial          Husband
7               Never-married      Prof-specialty    Not-in-family
8          Married-civ-spouse     Exec-managerial          Husband
9          Married-civ-spouse     Exec-managerial          Husband
10         Married-civ-spouse      Prof-specialty          Husband
11              Never-married        Adm-clerical        Own-child
12              Never-married               Sales    Not-in-family
13         Married-civ-spouse        Craft-repair          Husband
14         Married-civ-spouse    Transport-moving          Husband
15              Never-married     Farming-fishing        Own-child
16              Never-married   Machine-op-inspct        Unmarried
17         Married-civ-spouse               Sales          Husband
18                   Divorced     Exec-managerial        Unmarried
19         Married-civ-spouse      Prof-specialty          Husband
20                  Separated       Other-service        Unmarried
21         Married-civ-spouse     Farming-fishing          Husband
22         Married-civ-spouse    Transport-moving          Husband
23                   Divorced        Tech-support        Unmarried
24         Married-civ-spouse        Tech-support          Husband
25              Never-married        Craft-repair        Own-child
26         Married-civ-spouse                   ?          Husband
27                   Divorced     Exec-managerial    Not-in-family
28         Married-civ-spouse        Craft-repair          Husband
29              Never-married     Protective-serv    Not-in-family
...                       ...                 ...              ...
32530           Never-married                   ?    Not-in-family
32531      Married-civ-spouse      Prof-specialty          Husband
32532      Married-civ-spouse     Exec-managerial          Husband
32533                Divorced        Adm-clerical        Unmarried
32534           Never-married     Protective-serv        Own-child
32535           Never-married     Exec-managerial    Not-in-family
32536           Never-married        Craft-repair    Not-in-family
32537                Divorced      Prof-specialty        Unmarried
32538      Married-civ-spouse                   ?          Husband
32539               Separated        Adm-clerical        Own-child
32540               Separated                   ?    Not-in-family
32541      Married-civ-spouse                   ?          Husband
32542                Divorced      Prof-specialty        Unmarried
32543                Divorced       Other-service    Not-in-family
32544      Married-civ-spouse        Adm-clerical             Wife
32545                Divorced        Tech-support    Not-in-family
32546      Married-civ-spouse   Machine-op-inspct          Husband
32547           Never-married      Prof-specialty    Not-in-family
32548                Divorced        Adm-clerical   Other-relative
32549      Married-civ-spouse        Craft-repair          Husband
32550      Married-civ-spouse   Handlers-cleaners          Husband
32551      Married-civ-spouse               Sales          Husband
32552           Never-married        Tech-support    Not-in-family
32553      Married-civ-spouse     Exec-managerial          Husband
32554           Never-married     Protective-serv    Not-in-family
32555      Married-civ-spouse        Tech-support             Wife
32556      Married-civ-spouse   Machine-op-inspct          Husband
32557                 Widowed        Adm-clerical        Unmarried
32558           Never-married        Adm-clerical        Own-child
32559      Married-civ-spouse     Exec-managerial             Wife

                      race   gender     r1    r2  r3         country  salary
0                    White     Male      0     0  13   United-States   <=50K
1                    White     Male      0     0  40   United-States   <=50K
2                    Black     Male      0     0  40   United-States   <=50K
3                    Black   Female      0     0  40            Cuba   <=50K
4                    White   Female      0     0  40   United-States   <=50K
5                    Black   Female      0     0  16         Jamaica   <=50K
6                    White     Male      0     0  45   United-States    >50K
7                    White   Female  14084     0  50   United-States    >50K
8                    White     Male   5178     0  40   United-States    >50K
9                    Black     Male      0     0  80   United-States    >50K
10      Asian-Pac-Islander     Male      0     0  40           India    >50K
11                   White   Female      0     0  30   United-States   <=50K
12                   Black     Male      0     0  50   United-States   <=50K
13      Asian-Pac-Islander     Male      0     0  40               ?    >50K
14      Amer-Indian-Eskimo     Male      0     0  45          Mexico   <=50K
15                   White     Male      0     0  35   United-States   <=50K
16                   White     Male      0     0  40   United-States   <=50K
17                   White     Male      0     0  50   United-States   <=50K
18                   White   Female      0     0  45   United-States    >50K
19                   White     Male      0     0  60   United-States    >50K
20                   Black   Female      0     0  20   United-States   <=50K
21                   Black     Male      0     0  40   United-States   <=50K
22                   White     Male      0  2042  40   United-States   <=50K
23                   White   Female      0     0  40   United-States   <=50K
24                   White     Male      0     0  40   United-States    >50K
25                   White     Male      0     0  40   United-States   <=50K
26      Asian-Pac-Islander     Male      0     0  60           South    >50K
27                   White     Male      0     0  80   United-States   <=50K
28                   White     Male      0     0  40   United-States   <=50K
29                   White     Male      0     0  52   United-States   <=50K
...                    ...      ...    ...   ...  ..             ...     ...
32530   Asian-Pac-Islander   Female      0     0  99   United-States   <=50K
32531                White     Male      0     0  60   United-States    >50K
32532   Asian-Pac-Islander     Male      0     0  50           Japan    >50K
32533                White   Female      0     0  39   United-States   <=50K
32534                Black     Male      0     0  35   United-States   <=50K
32535                White   Female      0     0  55   United-States    >50K
32536                Black     Male      0     0  46   United-States   <=50K
32537                Black   Female  15020     0  45   United-States    >50K
32538                White     Male      0     0  10   United-States    >50K
32539                White   Female      0     0  40   United-States   <=50K
32540                Black   Female      0     0  32   United-States   <=50K
32541                White     Male      0     0  25   United-States   <=50K
32542                White   Female      0     0  48   United-States   <=50K
32543                Other   Female      0     0  30   United-States   <=50K
32544                White   Female      0     0  20   United-States    >50K
32545                White   Female      0     0  40   United-States   <=50K
32546                White     Male      0     0  40          Mexico   <=50K
32547                White     Male   1086     0  60   United-States   <=50K
32548                White   Female      0     0  40   United-States   <=50K
32549                White     Male      0     0  50   United-States   <=50K
32550   Amer-Indian-Eskimo     Male      0     0  40   United-States   <=50K
32551                White     Male      0     0  45   United-States   <=50K
32552   Asian-Pac-Islander     Male      0     0  11          Taiwan   <=50K
32553                White     Male      0     0  40   United-States    >50K
32554                White     Male      0     0  40   United-States   <=50K
32555                White   Female      0     0  38   United-States   <=50K
32556                White     Male      0     0  40   United-States    >50K
32557                White   Female      0     0  40   United-States   <=50K
32558                White     Male      0     0  20   United-States   <=50K
32559                White   Female  15024     0  40   United-States    >50K

[32560 rows x 15 columns]

In [179]:
#Task 2
query=connection.execute("update data SET age=20 WHERE Empid=83311; ")

In [180]:
updatequery=connection.execute("select * from data; ")
table=pd.DataFrame(updatequery.fetchall())
print(table)

          0   1                  2       3              4   5   \
0          0  20   Self-emp-not-inc   83311      Bachelors  13
1          1  38            Private  215646        HS-grad   9
2          2  53            Private  234721           11th   7
3          3  28            Private  338409      Bachelors  13
4          4  37            Private  284582        Masters  14
5          5  49            Private  160187            9th   5
6          6  52   Self-emp-not-inc  209642        HS-grad   9
7          7  31            Private   45781        Masters  14
8          8  42            Private  159449      Bachelors  13
9          9  37            Private  280464   Some-college  10
10        10  30          State-gov  141297      Bachelors  13
11        11  23            Private  122272      Bachelors  13
12        12  32            Private  205019     Assoc-acdm  12
13        13  40            Private  121772      Assoc-voc  11
14        14  34            Private  245487        7th-8th   4
15        15  25   Self-emp-not-inc  176756        HS-grad   9
16        16  32            Private  186824        HS-grad   9
17        17  38            Private   28887           11th   7
18        18  43   Self-emp-not-inc  292175        Masters  14
19        19  40            Private  193524      Doctorate  16
20        20  54            Private  302146        HS-grad   9
21        21  35        Federal-gov   76845            9th   5
22        22  43            Private  117037           11th   7
23        23  59            Private  109015        HS-grad   9
24        24  56          Local-gov  216851      Bachelors  13
25        25  19            Private  168294        HS-grad   9
26        26  54                  ?  180211   Some-college  10
27        27  39            Private  367260        HS-grad   9
28        28  49            Private  193366        HS-grad   9
29        29  23          Local-gov  190709     Assoc-acdm  12
...      ...  ..                ...     ...            ...  ..
32530  32530  30                  ?   33811      Bachelors  13
32531  32531  34            Private  204461      Doctorate  16
32532  32532  54            Private  337992      Bachelors  13
32533  32533  37            Private  179137   Some-college  10
32534  32534  22            Private  325033           12th   8
32535  32535  34            Private  160216      Bachelors  13
32536  32536  30            Private  345898        HS-grad   9
32537  32537  38            Private  139180      Bachelors  13
32538  32538  71                  ?  287372      Doctorate  16
32539  32539  45          State-gov  252208        HS-grad   9
32540  32540  41                  ?  202822        HS-grad   9
32541  32541  72                  ?  129912        HS-grad   9
32542  32542  45          Local-gov  119199     Assoc-acdm  12
32543  32543  31            Private  199655        Masters  14
32544  32544  39          Local-gov  111499     Assoc-acdm  12
32545  32545  37            Private  198216     Assoc-acdm  12
32546  32546  43            Private  260761        HS-grad   9
32547  32547  65   Self-emp-not-inc   99359    Prof-school  15
32548  32548  43          State-gov  255835   Some-college  10
32549  32549  43   Self-emp-not-inc   27242   Some-college  10
32550  32550  32            Private   34066           10th   6
32551  32551  43            Private   84661      Assoc-voc  11
32552  32552  32            Private  116138        Masters  14
32553  32553  53            Private  321865        Masters  14
32554  32554  22            Private  310152   Some-college  10
32555  32555  27            Private  257302     Assoc-acdm  12
32556  32556  40            Private  154374        HS-grad   9
32557  32557  58            Private  151910        HS-grad   9
32558  32558  22            Private  201490        HS-grad   9
32559  32559  52       Self-emp-inc  287927        HS-grad   9

                           6                   7                8   \
0          Married-civ-spouse     Exec-managerial          Husband
1                    Divorced   Handlers-cleaners    Not-in-family
2          Married-civ-spouse   Handlers-cleaners          Husband
3          Married-civ-spouse      Prof-specialty             Wife
4          Married-civ-spouse     Exec-managerial             Wife
5       Married-spouse-absent       Other-service    Not-in-family
6          Married-civ-spouse     Exec-managerial          Husband
7               Never-married      Prof-specialty    Not-in-family
8          Married-civ-spouse     Exec-managerial          Husband
9          Married-civ-spouse     Exec-managerial          Husband
10         Married-civ-spouse      Prof-specialty          Husband
11              Never-married        Adm-clerical        Own-child
12              Never-married               Sales    Not-in-family
13         Married-civ-spouse        Craft-repair          Husband
14         Married-civ-spouse    Transport-moving          Husband
15              Never-married     Farming-fishing        Own-child
16              Never-married   Machine-op-inspct        Unmarried
17         Married-civ-spouse               Sales          Husband
18                   Divorced     Exec-managerial        Unmarried
19         Married-civ-spouse      Prof-specialty          Husband
20                  Separated       Other-service        Unmarried
21         Married-civ-spouse     Farming-fishing          Husband
22         Married-civ-spouse    Transport-moving          Husband
23                   Divorced        Tech-support        Unmarried
24         Married-civ-spouse        Tech-support          Husband
25              Never-married        Craft-repair        Own-child
26         Married-civ-spouse                   ?          Husband
27                   Divorced     Exec-managerial    Not-in-family
28         Married-civ-spouse        Craft-repair          Husband
29              Never-married     Protective-serv    Not-in-family
...                       ...                 ...              ...
32530           Never-married                   ?    Not-in-family
32531      Married-civ-spouse      Prof-specialty          Husband
32532      Married-civ-spouse     Exec-managerial          Husband
32533                Divorced        Adm-clerical        Unmarried
32534           Never-married     Protective-serv        Own-child
32535           Never-married     Exec-managerial    Not-in-family
32536           Never-married        Craft-repair    Not-in-family
32537                Divorced      Prof-specialty        Unmarried
32538      Married-civ-spouse                   ?          Husband
32539               Separated        Adm-clerical        Own-child
32540               Separated                   ?    Not-in-family
32541      Married-civ-spouse                   ?          Husband
32542                Divorced      Prof-specialty        Unmarried
32543                Divorced       Other-service    Not-in-family
32544      Married-civ-spouse        Adm-clerical             Wife
32545                Divorced        Tech-support    Not-in-family
32546      Married-civ-spouse   Machine-op-inspct          Husband
32547           Never-married      Prof-specialty    Not-in-family
32548                Divorced        Adm-clerical   Other-relative
32549      Married-civ-spouse        Craft-repair          Husband
32550      Married-civ-spouse   Handlers-cleaners          Husband
32551      Married-civ-spouse               Sales          Husband
32552           Never-married        Tech-support    Not-in-family
32553      Married-civ-spouse     Exec-managerial          Husband
32554           Never-married     Protective-serv    Not-in-family
32555      Married-civ-spouse        Tech-support             Wife
32556      Married-civ-spouse   Machine-op-inspct          Husband
32557                 Widowed        Adm-clerical        Unmarried
32558           Never-married        Adm-clerical        Own-child
32559      Married-civ-spouse     Exec-managerial             Wife

                        9        10     11    12  13              14      15
0                    White     Male      0     0  13   United-States   <=50K
1                    White     Male      0     0  40   United-States   <=50K
2                    Black     Male      0     0  40   United-States   <=50K
3                    Black   Female      0     0  40            Cuba   <=50K
4                    White   Female      0     0  40   United-States   <=50K
5                    Black   Female      0     0  16         Jamaica   <=50K
6                    White     Male      0     0  45   United-States    >50K
7                    White   Female  14084     0  50   United-States    >50K
8                    White     Male   5178     0  40   United-States    >50K
9                    Black     Male      0     0  80   United-States    >50K
10      Asian-Pac-Islander     Male      0     0  40           India    >50K
11                   White   Female      0     0  30   United-States   <=50K
12                   Black     Male      0     0  50   United-States   <=50K
13      Asian-Pac-Islander     Male      0     0  40               ?    >50K
14      Amer-Indian-Eskimo     Male      0     0  45          Mexico   <=50K
15                   White     Male      0     0  35   United-States   <=50K
16                   White     Male      0     0  40   United-States   <=50K
17                   White     Male      0     0  50   United-States   <=50K
18                   White   Female      0     0  45   United-States    >50K
19                   White     Male      0     0  60   United-States    >50K
20                   Black   Female      0     0  20   United-States   <=50K
21                   Black     Male      0     0  40   United-States   <=50K
22                   White     Male      0  2042  40   United-States   <=50K
23                   White   Female      0     0  40   United-States   <=50K
24                   White     Male      0     0  40   United-States    >50K
25                   White     Male      0     0  40   United-States   <=50K
26      Asian-Pac-Islander     Male      0     0  60           South    >50K
27                   White     Male      0     0  80   United-States   <=50K
28                   White     Male      0     0  40   United-States   <=50K
29                   White     Male      0     0  52   United-States   <=50K
...                    ...      ...    ...   ...  ..             ...     ...
32530   Asian-Pac-Islander   Female      0     0  99   United-States   <=50K
32531                White     Male      0     0  60   United-States    >50K
32532   Asian-Pac-Islander     Male      0     0  50           Japan    >50K
32533                White   Female      0     0  39   United-States   <=50K
32534                Black     Male      0     0  35   United-States   <=50K
32535                White   Female      0     0  55   United-States    >50K
32536                Black     Male      0     0  46   United-States   <=50K
32537                Black   Female  15020     0  45   United-States    >50K
32538                White     Male      0     0  10   United-States    >50K
32539                White   Female      0     0  40   United-States   <=50K
32540                Black   Female      0     0  32   United-States   <=50K
32541                White     Male      0     0  25   United-States   <=50K
32542                White   Female      0     0  48   United-States   <=50K
32543                Other   Female      0     0  30   United-States   <=50K
32544                White   Female      0     0  20   United-States    >50K
32545                White   Female      0     0  40   United-States   <=50K
32546                White     Male      0     0  40          Mexico   <=50K
32547                White     Male   1086     0  60   United-States   <=50K
32548                White   Female      0     0  40   United-States   <=50K
32549                White     Male      0     0  50   United-States   <=50K
32550   Amer-Indian-Eskimo     Male      0     0  40   United-States   <=50K
32551                White     Male      0     0  45   United-States   <=50K
32552   Asian-Pac-Islander     Male      0     0  11          Taiwan   <=50K
32553                White     Male      0     0  40   United-States    >50K
32554                White     Male      0     0  40   United-States   <=50K
32555                White   Female      0     0  38   United-States   <=50K
32556                White     Male      0     0  40   United-States    >50K
32557                White   Female      0     0  40   United-States   <=50K
32558                White     Male      0     0  20   United-States   <=50K
32559                White   Female  15024     0  40   United-States    >50K

[32560 rows x 16 columns]

In [181]:
#Task 2

query=connection.execute("update data SET typeofjob='government' WHERE Empid=215646; ")
updatequery=connection.execute("select * from data; ")
table=pd.DataFrame(updatequery.fetchall())
print(table)

          0   1                  2       3              4   5   \
0          0  20   Self-emp-not-inc   83311      Bachelors  13
1          1  38         government  215646        HS-grad   9
2          2  53            Private  234721           11th   7
3          3  28            Private  338409      Bachelors  13
4          4  37            Private  284582        Masters  14
5          5  49            Private  160187            9th   5
6          6  52   Self-emp-not-inc  209642        HS-grad   9
7          7  31            Private   45781        Masters  14
8          8  42            Private  159449      Bachelors  13
9          9  37            Private  280464   Some-college  10
10        10  30          State-gov  141297      Bachelors  13
11        11  23            Private  122272      Bachelors  13
12        12  32            Private  205019     Assoc-acdm  12
13        13  40            Private  121772      Assoc-voc  11
14        14  34            Private  245487        7th-8th   4
15        15  25   Self-emp-not-inc  176756        HS-grad   9
16        16  32            Private  186824        HS-grad   9
17        17  38            Private   28887           11th   7
18        18  43   Self-emp-not-inc  292175        Masters  14
19        19  40            Private  193524      Doctorate  16
20        20  54            Private  302146        HS-grad   9
21        21  35        Federal-gov   76845            9th   5
22        22  43            Private  117037           11th   7
23        23  59            Private  109015        HS-grad   9
24        24  56          Local-gov  216851      Bachelors  13
25        25  19            Private  168294        HS-grad   9
26        26  54                  ?  180211   Some-college  10
27        27  39            Private  367260        HS-grad   9
28        28  49            Private  193366        HS-grad   9
29        29  23          Local-gov  190709     Assoc-acdm  12
...      ...  ..                ...     ...            ...  ..
32530  32530  30                  ?   33811      Bachelors  13
32531  32531  34            Private  204461      Doctorate  16
32532  32532  54            Private  337992      Bachelors  13
32533  32533  37            Private  179137   Some-college  10
32534  32534  22            Private  325033           12th   8
32535  32535  34            Private  160216      Bachelors  13
32536  32536  30            Private  345898        HS-grad   9
32537  32537  38            Private  139180      Bachelors  13
32538  32538  71                  ?  287372      Doctorate  16
32539  32539  45          State-gov  252208        HS-grad   9
32540  32540  41                  ?  202822        HS-grad   9
32541  32541  72                  ?  129912        HS-grad   9
32542  32542  45          Local-gov  119199     Assoc-acdm  12
32543  32543  31            Private  199655        Masters  14
32544  32544  39          Local-gov  111499     Assoc-acdm  12
32545  32545  37            Private  198216     Assoc-acdm  12
32546  32546  43            Private  260761        HS-grad   9
32547  32547  65   Self-emp-not-inc   99359    Prof-school  15
32548  32548  43          State-gov  255835   Some-college  10
32549  32549  43   Self-emp-not-inc   27242   Some-college  10
32550  32550  32            Private   34066           10th   6
32551  32551  43            Private   84661      Assoc-voc  11
32552  32552  32            Private  116138        Masters  14
32553  32553  53            Private  321865        Masters  14
32554  32554  22            Private  310152   Some-college  10
32555  32555  27            Private  257302     Assoc-acdm  12
32556  32556  40            Private  154374        HS-grad   9
32557  32557  58            Private  151910        HS-grad   9
32558  32558  22            Private  201490        HS-grad   9
32559  32559  52       Self-emp-inc  287927        HS-grad   9

                           6                   7                8   \
0          Married-civ-spouse     Exec-managerial          Husband
1                    Divorced   Handlers-cleaners    Not-in-family
2          Married-civ-spouse   Handlers-cleaners          Husband
3          Married-civ-spouse      Prof-specialty             Wife
4          Married-civ-spouse     Exec-managerial             Wife
5       Married-spouse-absent       Other-service    Not-in-family
6          Married-civ-spouse     Exec-managerial          Husband
7               Never-married      Prof-specialty    Not-in-family
8          Married-civ-spouse     Exec-managerial          Husband
9          Married-civ-spouse     Exec-managerial          Husband
10         Married-civ-spouse      Prof-specialty          Husband
11              Never-married        Adm-clerical        Own-child
12              Never-married               Sales    Not-in-family
13         Married-civ-spouse        Craft-repair          Husband
14         Married-civ-spouse    Transport-moving          Husband
15              Never-married     Farming-fishing        Own-child
16              Never-married   Machine-op-inspct        Unmarried
17         Married-civ-spouse               Sales          Husband
18                   Divorced     Exec-managerial        Unmarried
19         Married-civ-spouse      Prof-specialty          Husband
20                  Separated       Other-service        Unmarried
21         Married-civ-spouse     Farming-fishing          Husband
22         Married-civ-spouse    Transport-moving          Husband
23                   Divorced        Tech-support        Unmarried
24         Married-civ-spouse        Tech-support          Husband
25              Never-married        Craft-repair        Own-child
26         Married-civ-spouse                   ?          Husband
27                   Divorced     Exec-managerial    Not-in-family
28         Married-civ-spouse        Craft-repair          Husband
29              Never-married     Protective-serv    Not-in-family
...                       ...                 ...              ...
32530           Never-married                   ?    Not-in-family
32531      Married-civ-spouse      Prof-specialty          Husband
32532      Married-civ-spouse     Exec-managerial          Husband
32533                Divorced        Adm-clerical        Unmarried
32534           Never-married     Protective-serv        Own-child
32535           Never-married     Exec-managerial    Not-in-family
32536           Never-married        Craft-repair    Not-in-family
32537                Divorced      Prof-specialty        Unmarried
32538      Married-civ-spouse                   ?          Husband
32539               Separated        Adm-clerical        Own-child
32540               Separated                   ?    Not-in-family
32541      Married-civ-spouse                   ?          Husband
32542                Divorced      Prof-specialty        Unmarried
32543                Divorced       Other-service    Not-in-family
32544      Married-civ-spouse        Adm-clerical             Wife
32545                Divorced        Tech-support    Not-in-family
32546      Married-civ-spouse   Machine-op-inspct          Husband
32547           Never-married      Prof-specialty    Not-in-family
32548                Divorced        Adm-clerical   Other-relative
32549      Married-civ-spouse        Craft-repair          Husband
32550      Married-civ-spouse   Handlers-cleaners          Husband
32551      Married-civ-spouse               Sales          Husband
32552           Never-married        Tech-support    Not-in-family
32553      Married-civ-spouse     Exec-managerial          Husband
32554           Never-married     Protective-serv    Not-in-family
32555      Married-civ-spouse        Tech-support             Wife
32556      Married-civ-spouse   Machine-op-inspct          Husband
32557                 Widowed        Adm-clerical        Unmarried
32558           Never-married        Adm-clerical        Own-child
32559      Married-civ-spouse     Exec-managerial             Wife

                        9        10     11    12  13              14      15
0                    White     Male      0     0  13   United-States   <=50K
1                    White     Male      0     0  40   United-States   <=50K
2                    Black     Male      0     0  40   United-States   <=50K
3                    Black   Female      0     0  40            Cuba   <=50K
4                    White   Female      0     0  40   United-States   <=50K
5                    Black   Female      0     0  16         Jamaica   <=50K
6                    White     Male      0     0  45   United-States    >50K
7                    White   Female  14084     0  50   United-States    >50K
8                    White     Male   5178     0  40   United-States    >50K
9                    Black     Male      0     0  80   United-States    >50K
10      Asian-Pac-Islander     Male      0     0  40           India    >50K
11                   White   Female      0     0  30   United-States   <=50K
12                   Black     Male      0     0  50   United-States   <=50K
13      Asian-Pac-Islander     Male      0     0  40               ?    >50K
14      Amer-Indian-Eskimo     Male      0     0  45          Mexico   <=50K
15                   White     Male      0     0  35   United-States   <=50K
16                   White     Male      0     0  40   United-States   <=50K
17                   White     Male      0     0  50   United-States   <=50K
18                   White   Female      0     0  45   United-States    >50K
19                   White     Male      0     0  60   United-States    >50K
20                   Black   Female      0     0  20   United-States   <=50K
21                   Black     Male      0     0  40   United-States   <=50K
22                   White     Male      0  2042  40   United-States   <=50K
23                   White   Female      0     0  40   United-States   <=50K
24                   White     Male      0     0  40   United-States    >50K
25                   White     Male      0     0  40   United-States   <=50K
26      Asian-Pac-Islander     Male      0     0  60           South    >50K
27                   White     Male      0     0  80   United-States   <=50K
28                   White     Male      0     0  40   United-States   <=50K
29                   White     Male      0     0  52   United-States   <=50K
...                    ...      ...    ...   ...  ..             ...     ...
32530   Asian-Pac-Islander   Female      0     0  99   United-States   <=50K
32531                White     Male      0     0  60   United-States    >50K
32532   Asian-Pac-Islander     Male      0     0  50           Japan    >50K
32533                White   Female      0     0  39   United-States   <=50K
32534                Black     Male      0     0  35   United-States   <=50K
32535                White   Female      0     0  55   United-States    >50K
32536                Black     Male      0     0  46   United-States   <=50K
32537                Black   Female  15020     0  45   United-States    >50K
32538                White     Male      0     0  10   United-States    >50K
32539                White   Female      0     0  40   United-States   <=50K
32540                Black   Female      0     0  32   United-States   <=50K
32541                White     Male      0     0  25   United-States   <=50K
32542                White   Female      0     0  48   United-States   <=50K
32543                Other   Female      0     0  30   United-States   <=50K
32544                White   Female      0     0  20   United-States    >50K
32545                White   Female      0     0  40   United-States   <=50K
32546                White     Male      0     0  40          Mexico   <=50K
32547                White     Male   1086     0  60   United-States   <=50K
32548                White   Female      0     0  40   United-States   <=50K
32549                White     Male      0     0  50   United-States   <=50K
32550   Amer-Indian-Eskimo     Male      0     0  40   United-States   <=50K
32551                White     Male      0     0  45   United-States   <=50K
32552   Asian-Pac-Islander     Male      0     0  11          Taiwan   <=50K
32553                White     Male      0     0  40   United-States    >50K
32554                White     Male      0     0  40   United-States   <=50K
32555                White   Female      0     0  38   United-States   <=50K
32556                White     Male      0     0  40   United-States    >50K
32557                White   Female      0     0  40   United-States   <=50K
32558                White     Male      0     0  20   United-States   <=50K
32559                White   Female  15024     0  40   United-States    >50K

[32560 rows x 16 columns]

In [182]:
#Task 3

query=connection.execute("delete from data  WHERE Empid=234721; ")
updatequery=connection.execute("select * from data; ")
table=pd.DataFrame(updatequery.fetchall())
print(table)

          0   1                  2       3              4   5   \
0          0  20   Self-emp-not-inc   83311      Bachelors  13
1          1  38         government  215646        HS-grad   9
2          3  28            Private  338409      Bachelors  13
3          4  37            Private  284582        Masters  14
4          5  49            Private  160187            9th   5
5          6  52   Self-emp-not-inc  209642        HS-grad   9
6          7  31            Private   45781        Masters  14
7          8  42            Private  159449      Bachelors  13
8          9  37            Private  280464   Some-college  10
9         10  30          State-gov  141297      Bachelors  13
10        11  23            Private  122272      Bachelors  13
11        12  32            Private  205019     Assoc-acdm  12
12        13  40            Private  121772      Assoc-voc  11
13        14  34            Private  245487        7th-8th   4
14        15  25   Self-emp-not-inc  176756        HS-grad   9
15        16  32            Private  186824        HS-grad   9
16        17  38            Private   28887           11th   7
17        18  43   Self-emp-not-inc  292175        Masters  14
18        19  40            Private  193524      Doctorate  16
19        20  54            Private  302146        HS-grad   9
20        21  35        Federal-gov   76845            9th   5
21        22  43            Private  117037           11th   7
22        23  59            Private  109015        HS-grad   9
23        24  56          Local-gov  216851      Bachelors  13
24        25  19            Private  168294        HS-grad   9
25        26  54                  ?  180211   Some-college  10
26        27  39            Private  367260        HS-grad   9
27        28  49            Private  193366        HS-grad   9
28        29  23          Local-gov  190709     Assoc-acdm  12
29        30  20            Private  266015   Some-college  10
...      ...  ..                ...     ...            ...  ..
32529  32530  30                  ?   33811      Bachelors  13
32530  32531  34            Private  204461      Doctorate  16
32531  32532  54            Private  337992      Bachelors  13
32532  32533  37            Private  179137   Some-college  10
32533  32534  22            Private  325033           12th   8
32534  32535  34            Private  160216      Bachelors  13
32535  32536  30            Private  345898        HS-grad   9
32536  32537  38            Private  139180      Bachelors  13
32537  32538  71                  ?  287372      Doctorate  16
32538  32539  45          State-gov  252208        HS-grad   9
32539  32540  41                  ?  202822        HS-grad   9
32540  32541  72                  ?  129912        HS-grad   9
32541  32542  45          Local-gov  119199     Assoc-acdm  12
32542  32543  31            Private  199655        Masters  14
32543  32544  39          Local-gov  111499     Assoc-acdm  12
32544  32545  37            Private  198216     Assoc-acdm  12
32545  32546  43            Private  260761        HS-grad   9
32546  32547  65   Self-emp-not-inc   99359    Prof-school  15
32547  32548  43          State-gov  255835   Some-college  10
32548  32549  43   Self-emp-not-inc   27242   Some-college  10
32549  32550  32            Private   34066           10th   6
32550  32551  43            Private   84661      Assoc-voc  11
32551  32552  32            Private  116138        Masters  14
32552  32553  53            Private  321865        Masters  14
32553  32554  22            Private  310152   Some-college  10
32554  32555  27            Private  257302     Assoc-acdm  12
32555  32556  40            Private  154374        HS-grad   9
32556  32557  58            Private  151910        HS-grad   9
32557  32558  22            Private  201490        HS-grad   9
32558  32559  52       Self-emp-inc  287927        HS-grad   9

                           6                   7                8   \
0          Married-civ-spouse     Exec-managerial          Husband
1                    Divorced   Handlers-cleaners    Not-in-family
2          Married-civ-spouse      Prof-specialty             Wife
3          Married-civ-spouse     Exec-managerial             Wife
4       Married-spouse-absent       Other-service    Not-in-family
5          Married-civ-spouse     Exec-managerial          Husband
6               Never-married      Prof-specialty    Not-in-family
7          Married-civ-spouse     Exec-managerial          Husband
8          Married-civ-spouse     Exec-managerial          Husband
9          Married-civ-spouse      Prof-specialty          Husband
10              Never-married        Adm-clerical        Own-child
11              Never-married               Sales    Not-in-family
12         Married-civ-spouse        Craft-repair          Husband
13         Married-civ-spouse    Transport-moving          Husband
14              Never-married     Farming-fishing        Own-child
15              Never-married   Machine-op-inspct        Unmarried
16         Married-civ-spouse               Sales          Husband
17                   Divorced     Exec-managerial        Unmarried
18         Married-civ-spouse      Prof-specialty          Husband
19                  Separated       Other-service        Unmarried
20         Married-civ-spouse     Farming-fishing          Husband
21         Married-civ-spouse    Transport-moving          Husband
22                   Divorced        Tech-support        Unmarried
23         Married-civ-spouse        Tech-support          Husband
24              Never-married        Craft-repair        Own-child
25         Married-civ-spouse                   ?          Husband
26                   Divorced     Exec-managerial    Not-in-family
27         Married-civ-spouse        Craft-repair          Husband
28              Never-married     Protective-serv    Not-in-family
29              Never-married               Sales        Own-child
...                       ...                 ...              ...
32529           Never-married                   ?    Not-in-family
32530      Married-civ-spouse      Prof-specialty          Husband
32531      Married-civ-spouse     Exec-managerial          Husband
32532                Divorced        Adm-clerical        Unmarried
32533           Never-married     Protective-serv        Own-child
32534           Never-married     Exec-managerial    Not-in-family
32535           Never-married        Craft-repair    Not-in-family
32536                Divorced      Prof-specialty        Unmarried
32537      Married-civ-spouse                   ?          Husband
32538               Separated        Adm-clerical        Own-child
32539               Separated                   ?    Not-in-family
32540      Married-civ-spouse                   ?          Husband
32541                Divorced      Prof-specialty        Unmarried
32542                Divorced       Other-service    Not-in-family
32543      Married-civ-spouse        Adm-clerical             Wife
32544                Divorced        Tech-support    Not-in-family
32545      Married-civ-spouse   Machine-op-inspct          Husband
32546           Never-married      Prof-specialty    Not-in-family
32547                Divorced        Adm-clerical   Other-relative
32548      Married-civ-spouse        Craft-repair          Husband
32549      Married-civ-spouse   Handlers-cleaners          Husband
32550      Married-civ-spouse               Sales          Husband
32551           Never-married        Tech-support    Not-in-family
32552      Married-civ-spouse     Exec-managerial          Husband
32553           Never-married     Protective-serv    Not-in-family
32554      Married-civ-spouse        Tech-support             Wife
32555      Married-civ-spouse   Machine-op-inspct          Husband
32556                 Widowed        Adm-clerical        Unmarried
32557           Never-married        Adm-clerical        Own-child
32558      Married-civ-spouse     Exec-managerial             Wife

                        9        10     11    12  13              14      15
0                    White     Male      0     0  13   United-States   <=50K
1                    White     Male      0     0  40   United-States   <=50K
2                    Black   Female      0     0  40            Cuba   <=50K
3                    White   Female      0     0  40   United-States   <=50K
4                    Black   Female      0     0  16         Jamaica   <=50K
5                    White     Male      0     0  45   United-States    >50K
6                    White   Female  14084     0  50   United-States    >50K
7                    White     Male   5178     0  40   United-States    >50K
8                    Black     Male      0     0  80   United-States    >50K
9       Asian-Pac-Islander     Male      0     0  40           India    >50K
10                   White   Female      0     0  30   United-States   <=50K
11                   Black     Male      0     0  50   United-States   <=50K
12      Asian-Pac-Islander     Male      0     0  40               ?    >50K
13      Amer-Indian-Eskimo     Male      0     0  45          Mexico   <=50K
14                   White     Male      0     0  35   United-States   <=50K
15                   White     Male      0     0  40   United-States   <=50K
16                   White     Male      0     0  50   United-States   <=50K
17                   White   Female      0     0  45   United-States    >50K
18                   White     Male      0     0  60   United-States    >50K
19                   Black   Female      0     0  20   United-States   <=50K
20                   Black     Male      0     0  40   United-States   <=50K
21                   White     Male      0  2042  40   United-States   <=50K
22                   White   Female      0     0  40   United-States   <=50K
23                   White     Male      0     0  40   United-States    >50K
24                   White     Male      0     0  40   United-States   <=50K
25      Asian-Pac-Islander     Male      0     0  60           South    >50K
26                   White     Male      0     0  80   United-States   <=50K
27                   White     Male      0     0  40   United-States   <=50K
28                   White     Male      0     0  52   United-States   <=50K
29                   Black     Male      0     0  44   United-States   <=50K
...                    ...      ...    ...   ...  ..             ...     ...
32529   Asian-Pac-Islander   Female      0     0  99   United-States   <=50K
32530                White     Male      0     0  60   United-States    >50K
32531   Asian-Pac-Islander     Male      0     0  50           Japan    >50K
32532                White   Female      0     0  39   United-States   <=50K
32533                Black     Male      0     0  35   United-States   <=50K
32534                White   Female      0     0  55   United-States    >50K
32535                Black     Male      0     0  46   United-States   <=50K
32536                Black   Female  15020     0  45   United-States    >50K
32537                White     Male      0     0  10   United-States    >50K
32538                White   Female      0     0  40   United-States   <=50K
32539                Black   Female      0     0  32   United-States   <=50K
32540                White     Male      0     0  25   United-States   <=50K
32541                White   Female      0     0  48   United-States   <=50K
32542                Other   Female      0     0  30   United-States   <=50K
32543                White   Female      0     0  20   United-States    >50K
32544                White   Female      0     0  40   United-States   <=50K
32545                White     Male      0     0  40          Mexico   <=50K
32546                White     Male   1086     0  60   United-States   <=50K
32547                White   Female      0     0  40   United-States   <=50K
32548                White     Male      0     0  50   United-States   <=50K
32549   Amer-Indian-Eskimo     Male      0     0  40   United-States   <=50K
32550                White     Male      0     0  45   United-States   <=50K
32551   Asian-Pac-Islander     Male      0     0  11          Taiwan   <=50K
32552                White     Male      0     0  40   United-States    >50K
32553                White     Male      0     0  40   United-States   <=50K
32554                White   Female      0     0  38   United-States   <=50K
32555                White     Male      0     0  40   United-States    >50K
32556                White   Female      0     0  40   United-States   <=50K
32557                White     Male      0     0  20   United-States   <=50K
32558                White   Female  15024     0  40   United-States    >50K

[32559 rows x 16 columns]

In [183]:
#Task 3

query=connection.execute("delete from data  WHERE Empid=338409; ")
updatequery=connection.execute("select * from data; ")
table=pd.DataFrame(updatequery.fetchall())
print(table)

          0   1                  2       3              4   5   \
0          0  20   Self-emp-not-inc   83311      Bachelors  13
1          1  38         government  215646        HS-grad   9
2          4  37            Private  284582        Masters  14
3          5  49            Private  160187            9th   5
4          6  52   Self-emp-not-inc  209642        HS-grad   9
5          7  31            Private   45781        Masters  14
6          8  42            Private  159449      Bachelors  13
7          9  37            Private  280464   Some-college  10
8         10  30          State-gov  141297      Bachelors  13
9         11  23            Private  122272      Bachelors  13
10        12  32            Private  205019     Assoc-acdm  12
11        13  40            Private  121772      Assoc-voc  11
12        14  34            Private  245487        7th-8th   4
13        15  25   Self-emp-not-inc  176756        HS-grad   9
14        16  32            Private  186824        HS-grad   9
15        17  38            Private   28887           11th   7
16        18  43   Self-emp-not-inc  292175        Masters  14
17        19  40            Private  193524      Doctorate  16
18        20  54            Private  302146        HS-grad   9
19        21  35        Federal-gov   76845            9th   5
20        22  43            Private  117037           11th   7
21        23  59            Private  109015        HS-grad   9
22        24  56          Local-gov  216851      Bachelors  13
23        25  19            Private  168294        HS-grad   9
24        26  54                  ?  180211   Some-college  10
25        27  39            Private  367260        HS-grad   9
26        28  49            Private  193366        HS-grad   9
27        29  23          Local-gov  190709     Assoc-acdm  12
28        30  20            Private  266015   Some-college  10
29        31  45            Private  386940      Bachelors  13
...      ...  ..                ...     ...            ...  ..
32528  32530  30                  ?   33811      Bachelors  13
32529  32531  34            Private  204461      Doctorate  16
32530  32532  54            Private  337992      Bachelors  13
32531  32533  37            Private  179137   Some-college  10
32532  32534  22            Private  325033           12th   8
32533  32535  34            Private  160216      Bachelors  13
32534  32536  30            Private  345898        HS-grad   9
32535  32537  38            Private  139180      Bachelors  13
32536  32538  71                  ?  287372      Doctorate  16
32537  32539  45          State-gov  252208        HS-grad   9
32538  32540  41                  ?  202822        HS-grad   9
32539  32541  72                  ?  129912        HS-grad   9
32540  32542  45          Local-gov  119199     Assoc-acdm  12
32541  32543  31            Private  199655        Masters  14
32542  32544  39          Local-gov  111499     Assoc-acdm  12
32543  32545  37            Private  198216     Assoc-acdm  12
32544  32546  43            Private  260761        HS-grad   9
32545  32547  65   Self-emp-not-inc   99359    Prof-school  15
32546  32548  43          State-gov  255835   Some-college  10
32547  32549  43   Self-emp-not-inc   27242   Some-college  10
32548  32550  32            Private   34066           10th   6
32549  32551  43            Private   84661      Assoc-voc  11
32550  32552  32            Private  116138        Masters  14
32551  32553  53            Private  321865        Masters  14
32552  32554  22            Private  310152   Some-college  10
32553  32555  27            Private  257302     Assoc-acdm  12
32554  32556  40            Private  154374        HS-grad   9
32555  32557  58            Private  151910        HS-grad   9
32556  32558  22            Private  201490        HS-grad   9
32557  32559  52       Self-emp-inc  287927        HS-grad   9

                           6                   7                8   \
0          Married-civ-spouse     Exec-managerial          Husband
1                    Divorced   Handlers-cleaners    Not-in-family
2          Married-civ-spouse     Exec-managerial             Wife
3       Married-spouse-absent       Other-service    Not-in-family
4          Married-civ-spouse     Exec-managerial          Husband
5               Never-married      Prof-specialty    Not-in-family
6          Married-civ-spouse     Exec-managerial          Husband
7          Married-civ-spouse     Exec-managerial          Husband
8          Married-civ-spouse      Prof-specialty          Husband
9               Never-married        Adm-clerical        Own-child
10              Never-married               Sales    Not-in-family
11         Married-civ-spouse        Craft-repair          Husband
12         Married-civ-spouse    Transport-moving          Husband
13              Never-married     Farming-fishing        Own-child
14              Never-married   Machine-op-inspct        Unmarried
15         Married-civ-spouse               Sales          Husband
16                   Divorced     Exec-managerial        Unmarried
17         Married-civ-spouse      Prof-specialty          Husband
18                  Separated       Other-service        Unmarried
19         Married-civ-spouse     Farming-fishing          Husband
20         Married-civ-spouse    Transport-moving          Husband
21                   Divorced        Tech-support        Unmarried
22         Married-civ-spouse        Tech-support          Husband
23              Never-married        Craft-repair        Own-child
24         Married-civ-spouse                   ?          Husband
25                   Divorced     Exec-managerial    Not-in-family
26         Married-civ-spouse        Craft-repair          Husband
27              Never-married     Protective-serv    Not-in-family
28              Never-married               Sales        Own-child
29                   Divorced     Exec-managerial        Own-child
...                       ...                 ...              ...
32528           Never-married                   ?    Not-in-family
32529      Married-civ-spouse      Prof-specialty          Husband
32530      Married-civ-spouse     Exec-managerial          Husband
32531                Divorced        Adm-clerical        Unmarried
32532           Never-married     Protective-serv        Own-child
32533           Never-married     Exec-managerial    Not-in-family
32534           Never-married        Craft-repair    Not-in-family
32535                Divorced      Prof-specialty        Unmarried
32536      Married-civ-spouse                   ?          Husband
32537               Separated        Adm-clerical        Own-child
32538               Separated                   ?    Not-in-family
32539      Married-civ-spouse                   ?          Husband
32540                Divorced      Prof-specialty        Unmarried
32541                Divorced       Other-service    Not-in-family
32542      Married-civ-spouse        Adm-clerical             Wife
32543                Divorced        Tech-support    Not-in-family
32544      Married-civ-spouse   Machine-op-inspct          Husband
32545           Never-married      Prof-specialty    Not-in-family
32546                Divorced        Adm-clerical   Other-relative
32547      Married-civ-spouse        Craft-repair          Husband
32548      Married-civ-spouse   Handlers-cleaners          Husband
32549      Married-civ-spouse               Sales          Husband
32550           Never-married        Tech-support    Not-in-family
32551      Married-civ-spouse     Exec-managerial          Husband
32552           Never-married     Protective-serv    Not-in-family
32553      Married-civ-spouse        Tech-support             Wife
32554      Married-civ-spouse   Machine-op-inspct          Husband
32555                 Widowed        Adm-clerical        Unmarried
32556           Never-married        Adm-clerical        Own-child
32557      Married-civ-spouse     Exec-managerial             Wife

                        9        10     11    12  13              14      15
0                    White     Male      0     0  13   United-States   <=50K
1                    White     Male      0     0  40   United-States   <=50K
2                    White   Female      0     0  40   United-States   <=50K
3                    Black   Female      0     0  16         Jamaica   <=50K
4                    White     Male      0     0  45   United-States    >50K
5                    White   Female  14084     0  50   United-States    >50K
6                    White     Male   5178     0  40   United-States    >50K
7                    Black     Male      0     0  80   United-States    >50K
8       Asian-Pac-Islander     Male      0     0  40           India    >50K
9                    White   Female      0     0  30   United-States   <=50K
10                   Black     Male      0     0  50   United-States   <=50K
11      Asian-Pac-Islander     Male      0     0  40               ?    >50K
12      Amer-Indian-Eskimo     Male      0     0  45          Mexico   <=50K
13                   White     Male      0     0  35   United-States   <=50K
14                   White     Male      0     0  40   United-States   <=50K
15                   White     Male      0     0  50   United-States   <=50K
16                   White   Female      0     0  45   United-States    >50K
17                   White     Male      0     0  60   United-States    >50K
18                   Black   Female      0     0  20   United-States   <=50K
19                   Black     Male      0     0  40   United-States   <=50K
20                   White     Male      0  2042  40   United-States   <=50K
21                   White   Female      0     0  40   United-States   <=50K
22                   White     Male      0     0  40   United-States    >50K
23                   White     Male      0     0  40   United-States   <=50K
24      Asian-Pac-Islander     Male      0     0  60           South    >50K
25                   White     Male      0     0  80   United-States   <=50K
26                   White     Male      0     0  40   United-States   <=50K
27                   White     Male      0     0  52   United-States   <=50K
28                   Black     Male      0     0  44   United-States   <=50K
29                   White     Male      0  1408  40   United-States   <=50K
...                    ...      ...    ...   ...  ..             ...     ...
32528   Asian-Pac-Islander   Female      0     0  99   United-States   <=50K
32529                White     Male      0     0  60   United-States    >50K
32530   Asian-Pac-Islander     Male      0     0  50           Japan    >50K
32531                White   Female      0     0  39   United-States   <=50K
32532                Black     Male      0     0  35   United-States   <=50K
32533                White   Female      0     0  55   United-States    >50K
32534                Black     Male      0     0  46   United-States   <=50K
32535                Black   Female  15020     0  45   United-States    >50K
32536                White     Male      0     0  10   United-States    >50K
32537                White   Female      0     0  40   United-States   <=50K
32538                Black   Female      0     0  32   United-States   <=50K
32539                White     Male      0     0  25   United-States   <=50K
32540                White   Female      0     0  48   United-States   <=50K
32541                Other   Female      0     0  30   United-States   <=50K
32542                White   Female      0     0  20   United-States    >50K
32543                White   Female      0     0  40   United-States   <=50K
32544                White     Male      0     0  40          Mexico   <=50K
32545                White     Male   1086     0  60   United-States   <=50K
32546                White   Female      0     0  40   United-States   <=50K
32547                White     Male      0     0  50   United-States   <=50K
32548   Amer-Indian-Eskimo     Male      0     0  40   United-States   <=50K
32549                White     Male      0     0  45   United-States   <=50K
32550   Asian-Pac-Islander     Male      0     0  11          Taiwan   <=50K
32551                White     Male      0     0  40   United-States    >50K
32552                White     Male      0     0  40   United-States   <=50K
32553                White   Female      0     0  38   United-States   <=50K
32554                White     Male      0     0  40   United-States    >50K
32555                White   Female      0     0  40   United-States   <=50K
32556                White     Male      0     0  20   United-States   <=50K
32557                White   Female  15024     0  40   United-States    >50K

[32558 rows x 16 columns]

In [205]:
#Task 4

table_query=connection.execute("select * from data where typeofjob='government';")
table=pd.DataFrame(table_query.fetchall())
print(table)

   0   1           2       3         4   5          6                   7   \
0   1  38  government  215646   HS-grad   9   Divorced   Handlers-cleaners

               8       9      10  11  12  13              14      15
0   Not-in-family   White   Male   0   0  40   United-States   <=50K

In [208]:
#Task 4

table_query=connection.execute("select * from data where Empid=83311;")
table=pd.DataFrame(table_query.fetchall())
print(table)

      0   1                  2      3             4   5                    6   \
0      0  20   Self-emp-not-inc  83311     Bachelors  13   Married-civ-spouse
1  16473  20   Self-emp-not-inc  83311   Prof-school  15   Married-civ-spouse

                 7         8       9      10  11  12  13              14  \
0   Exec-managerial   Husband   White   Male   0   0  13   United-States
1    Prof-specialty   Husband   White   Male   0   0  30   United-States

       15
0   <=50K
1    >50K

In [15]:
#Task 5

table_query=connection.execute("select count(Empid) from data;")
table=pd.DataFrame(table_query.fetchall())
print(table)

       0
0  32560

In [19]:
#Task 5

table_query=connection.execute("select avg(age) from data;")
table=pd.DataFrame(table_query.fetchall())
print(table)

           0
0  38.581634